name: Actualizar Lenguajes Perfil

on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta cada medianoche
  workflow_dispatch: # Permite darle Play manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generar Gráfico de Lenguajes Nativos
        uses: teoxoy/profile-readme-stats@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Esto buscará tus marcas en el README para meter el gráfico
          readme_path: README.md
